branches:
  only:
    - main
language: node_js
node_js:
  - 16

services:
  - docker

script:
## Build
  - docker-compose -f docker-compose-build.yaml build
## Tagging
  - docker tag udagram-api-feed phantuanvi/udagram-api-feed:latest
  - docker tag udagram-api-user phantuanvi/udagram-api-user:latest
  - docker tag udagram-frontend phantuanvi/udagram-frontend:latest
  - docker tag reverseproxy phantuanvi/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
## Push
  - docker push phantuanvi/udagram-api-feed
  - docker push phantuanvi/udagram-api-user
  - docker push phantuanvi/udagram-frontend
  - docker push phantuanvi/reverseproxy